isPublic: false
name: Astro
scope:
  - 'sites.8153a2df-373f-4aac-9a92-d52292c9f1aa:read' # Baukasten (en)
  - 'sites.b205e203-99d0-4ee4-b75c-90a868606c4b:read' # Baukasten (de)
  - 'sites.f9ec1fe5-6806-433d-b5e2-6aef4d148b23:read'
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.e5172a18-ed16-4229-89ca-fc0dc776597a:read' # Error Pages
  - 'entrytypes.8ced5be5-13b2-483f-8db9-aab9757aad21:read' # Error
  - 'sections.a5117399-7fb7-455d-ae51-92ebf3c1b696:read' # Home
  - 'entrytypes.a67a951e-14fb-4e12-99ed-3b1c9e6cf92e:read' # Home
  - 'sections.3547e7b4-f3fb-4cf4-9d29-9f12dfa94594:read' # News
  - 'entrytypes.fb701216-3e80-4e6d-99d4-2e5f70561e22:read' # Content Builder
  - 'sections.b0207f48-be48-49ab-a759-1ff51f232df3:read' # Pages
  - 'entrytypes.2f642060-4792-41cb-a427-083aabeba231:read' # Content Builder
  - 'entrytypes.6d94dcc4-6ec1-45b4-8c86-e53cee842b11:read' # Overview News
  - 'volumes.6c5fc0dd-cf56-48d8-8af8-88abe763b970:read' # Files
  - 'volumes.f1b38495-8096-48fa-9b78-0da345e3295c:read' # Images
  - 'volumes.77c74b5c-6bbb-41a7-b166-c6b158a3cc7f:read' # Template Images
  - 'volumes.8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6:read' # Users
  - 'usergroups.everyone:read'
  - 'formieForms.all:read'
  - 'formieForms.56e2dea4-d25e-496d-b053-48387e824b07:read'
  - 'formieSubmissions.all:read'
  - 'formieSubmissions.56e2dea4-d25e-496d-b053-48387e824b07:read'
  - 'navigationNavs.all:read'
  - 'navigationNavs.7adefd56-3873-4a7f-9d5e-b4bfdafddf9d:read' # Navigation Main
  - 'seomatic.all:read'
